polyCylinder -r 0.5 -h 10 -sx 20 -sy 10 -sz 5 -ax 0 1 0 -rcp 0 -cuv 3 -ch 1;
move -r 0 5 0;

polyCone -r 3 -h 4 -sc 10;
move -r 0 7 0;

softSelect -sse 1;
softSelect -ssd 2;

select -r "pCone1.vtx[20:39]";
move -r -x 0 -y 0.5 -z 0;
softSelect -sse 0;


polyCone -r 2.75 -h 3.75;
move -r 0 8 0;
scale -r 0.90 0.90 0.90;


polyCone -r 2.5 -h 3.5;
move -r 0 9 0;
scale -r 0.66 0.66 0.66;

polyCone -r 2 -h 3;
move -r  0 10 0;
scale -r 0.5 0.5 0.5;
